const CREATE_NEW_TODO = 'CREATE_NEW_TODO'
const CHNAGE_TODO_FINISH = 'CHNAGE_TODO_FINISH'
const REMOVE_TODO = 'REMOVE_TODO'
const ADD_TODO = 'ADD_TODO'

export {CREATE_NEW_TODO,CHNAGE_TODO_FINISH,REMOVE_TODO,ADD_TODO}